globalConfig:
  signing_key: 0b5517da-9839-427c-8cc3-9daa6091c1ac
  account_id: f1fc1606-5e9a-4920-a661-838a1218ed90
sinksConfig:
  - robusta_sink:
      name: robusta_ui_sink
      token: eyJhY2NvdW50X2lkIjogImYxZmMxNjA2LTVlOWEtNDkyMC1hNjYxLTgzOGExMjE4ZWQ5MCIsICJhcGlfa2V5IjogImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUp5YjJ4bElqb2lZVzV2YmlJc0ltbGhkQ0k2TVRZeU5ERTNNalF5TkN3aVpYaHdJam94T1RNNU56UTROREkwZlEuaFJMdjZQQW54MWNhdkR3bC1pWXlnQXJINHFBMERWSFluckQ3MUFzcXFQdyIsICJzdG9yZV91cmwiOiAiaHR0cHM6Ly94dnlocG94Zm10cHVxcWV5cWtzby5zdXBhYmFzZS5jbyIsICJlbWFpbCI6ICJhcGl1c2VyLXJvYnVzdGEtYXNoLTU5Nzk3N0Byb2J1c3RhLmRldiIsICJwYXNzd29yZCI6ICI4ZmFlM2M2ZC05MDk2LTQwNjYtOTM3NS00ZDJlM2I0MjZjY2YifQ==
enablePrometheusStack: false
enablePlatformPlaybooks: true
runner:
  sendAdditionalTelemetry: false
  additional_env_vars: []
