name: Scan
on:
  workflow_dispatch  
jobs:
  security:
    runs-on: ubuntu-latest
    steps: 
      # Checkout the repository
      - uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t node-chat:${{ github.sha }} .

      # Run Snyk to monitor Node.js project (optional, monitor tracks for future vulnerabilities)
      - name: Monitor Node.js Project with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
        continue-on-error: true

      # Run Snyk on Docker image for vulnerabilities
      - name: Check Docker Image for Vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: node-chat:${{ github.sha }}
          args: monitor
        continue-on-error: true
